local M = function(p, opts)
	local bg = opts.transparent and "NONE" or p.background
	local surface0 = opts.transparent and "NONE" or p.surface0
	local surface1 = opts.transparent and "NONE" or p.surface1
	local highlights = {

		-- Editor
		Normal = { fg = p.foreground, bg = bg },
		NormalFloat = { fg = p.foreground, bg = surface0 },
		NormalNC = { fg = p.second_text, bg = bg },
		ColorColumn = { bg = surface1 },
		Conceal = { fg = p.third_text },
		Cursor = { fg = p.background, bg = p.foreground },
		CursorIM = { fg = p.background, bg = p.foreground },
		CursorColumn = { bg = surface0 },
		CursorLine = { bg = surface0 },
		CursorLineNr = { fg = p.yellow, bold = true },
		Directory = { fg = p.blue },
		EndOfBuffer = { fg = p.surface1 },
		ErrorMsg = { fg = p.red, bold = true },
		FloatBorder = { fg = p.surface2, bg = surface0 },
		FloatTitle = { fg = p.foreground, bg = surface0 },
		FoldColumn = { fg = p.third_text, bg = bg },
		Folded = { fg = p.third_text, bg = surface0 },
		LineNr = { fg = p.surface2 },
		MatchParen = { fg = p.yellow, bold = true, underline = true },
		ModeMsg = { fg = p.foreground, bold = true },
		MoreMsg = { fg = p.green },
		MsgArea = { fg = p.foreground },
		NonText = { fg = p.surface2 },
		Pmenu = { fg = p.foreground, bg = surface0 },
		PmenuSbar = { bg = surface1 },
		PmenuSel = { fg = p.background, bg = p.blue },
		PmenuThumb = { bg = p.surface2 },
		Question = { fg = p.green },
		QuickFixLine = { bg = surface1 },
		Search = { fg = p.background, bg = p.yellow },
		IncSearch = { fg = p.background, bg = p.bright_yellow },
		CurSearch = { fg = p.background, bg = p.bright_yellow },
		SignColumn = { fg = p.third_text, bg = bg },
		SpecialKey = { fg = p.surface2 },
		SpellBad = { undercurl = true, sp = p.red },
		SpellCap = { undercurl = true, sp = p.yellow },
		SpellLocal = { undercurl = true, sp = p.blue },
		SpellRare = { undercurl = true, sp = p.violet },
		StatusLine = { fg = p.foreground, bg = surface1 },
		StatusLineNC = { fg = p.third_text, bg = surface0 },
		Substitute = { fg = p.background, bg = p.red },
		TabLine = { fg = p.third_text, bg = surface0 },
		TabLineFill = { bg = bg },
		TabLineSel = { fg = p.foreground, bg = surface1, bold = true },
		Title = { fg = p.foreground, bold = true },
		VertSplit = { fg = p.surface2 },
		WinSeparator = { fg = p.surface2 },
		Visual = { bg = p.surface2 },
		VisualNOS = { bg = surface1 },
		WarningMsg = { fg = p.yellow },
		Whitespace = { fg = p.surface2 },
		WildMenu = { fg = p.background, bg = p.blue },
		WinBar = { fg = p.second_text, bg = bg },
		WinBarNC = { fg = p.third_text, bg = bg },

		-- Syntax
		Comment = { fg = p.third_text, italic = true },
		Constant = { fg = p.yellow },
		String = { fg = p.green },
		Character = { fg = p.green },
		Number = { fg = p.yellow },
		Float = { fg = p.yellow },
		Boolean = { fg = p.yellow },
		Identifier = { fg = p.cyan },
		Function = { fg = p.blue },
		Statement = { fg = p.red },
		Conditional = { fg = p.red },
		Repeat = { fg = p.red },
		Label = { fg = p.red },
		Operator = { fg = p.white },
		Keyword = { fg = p.red, bold = true },
		Exception = { fg = p.red },
		PreProc = { fg = p.violet },
		Include = { fg = p.violet },
		Define = { fg = p.violet },
		Macro = { fg = p.violet },
		PreCondit = { fg = p.violet },
		Type = { fg = p.bright_cyan },
		StorageClass = { fg = p.bright_cyan },
		Structure = { fg = p.bright_cyan },
		Typedef = { fg = p.bright_cyan },
		Special = { fg = p.yellow },
		SpecialChar = { fg = p.yellow },
		Tag = { fg = p.blue },
		Delimiter = { fg = p.white },
		SpecialComment = { fg = p.third_text, italic = true },
		Debug = { fg = p.red },
		Underlined = { underline = true },
		Ignore = { fg = p.surface2 },
		Error = { fg = p.red, bold = true },
		Todo = { fg = p.background, bg = p.yellow, bold = true },

		-- Diagnostics
		DiagnosticError = { fg = p.red },
		DiagnosticWarn = { fg = p.yellow },
		DiagnosticInfo = { fg = p.blue },
		DiagnosticHint = { fg = p.cyan },
		DiagnosticOk = { fg = p.green },
		DiagnosticUnderlineError = { undercurl = true, sp = p.red },
		DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
		DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
		DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },
		DiagnosticVirtualTextError = { fg = p.red, bg = surface0 },
		DiagnosticVirtualTextWarn = { fg = p.yellow, bg = surface0 },
		DiagnosticVirtualTextInfo = { fg = p.blue, bg = surface0 },
		DiagnosticVirtualTextHint = { fg = p.cyan, bg = surface0 },
		DiagnosticSignError = { fg = p.red },
		DiagnosticSignWarn = { fg = p.yellow },
		DiagnosticSignInfo = { fg = p.blue },
		DiagnosticSignHint = { fg = p.cyan },

		-- Git
		DiffAdd = { fg = p.green, bg = surface0 },
		DiffChange = { fg = p.yellow, bg = surface0 },
		DiffDelete = { fg = p.red, bg = surface0 },
		DiffText = { fg = p.foreground, bg = surface1 },
		GitSignsAdd = { fg = p.green },
		GitSignsChange = { fg = p.yellow },
		GitSignsDelete = { fg = p.red },
	}

	for group, hl_opts in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, hl_opts)
	end
end

return M
